USE [InventoryManagement]
GO
INSERT INTO [dbo].[tlkp_CutNames] (CutName)
VALUES ('Darted Bodice'),
('self supporting'),
('gored'),
('Princess seam'),
('square cut'),
('houpeland'),
('polonaise'),
('2 panel bodice'),
('half circle'),
('T tunic'),
('shaped yolk'),
('circle'),
('bustle'),
('Darted'),
('maternety'),
('crescent'),
('corded petticoat'),
('4 panel'),
('mermaid tail'),
('fly fishing'),
('unshaped bodice'),
('corded'),
('hooded'),
('squre cut'),
('bias'),
('3 tiered'),
('newsie with brim'),
('scout'),
('support'),
('hobble'),
('pleated'),
('empire waist'),
('peplum'),
('flared collar'),
('square dance'),
('gunnie sax'),
('airline'),
('mandarin collar'),
('2 panel'),
('v-neck'),
('flat front'),
('square neck'),
('fitted, tie on'),
('puffed, tied on'),
('cap with veil'),
('net snood'),
('4 gore'),
('scoop neck'),
('square neck, laced opening'),
('gable style'),
('high crown'),
('Square neck, set in sleeve with cuff'),
('full, tie on'),
('french hood'),
('tassel and rope'),
('large flemish kerchif'),
('small kerchif'),
('elastic waist'),
('ghilli brouge'),
('leg wraps'),
('bib front'),
('coif'),
('sleeveless'),
('back laced'),
('farthingale'),
('square neckline, set in sleeve'),
('high collar'),
('lace and twist'),
('layered turkish'),
('uncommon gardening'),
('two color Norwegian'),
('winter twilight'),
('motley Mitts'),
('mittens, inturupted'),
('fringed, triangle'),
('covered'),
('2 piece'),
('pleated cuff'),
('pleated bodice'),
('white'),
('peaked center'),
('full, cuff'),
('scoop'),
('bust and hip gores'),
('jewel neck darted '),
('v-neck darted'),
('Tucked '),
('pullover'),
('gathered cuff'),
('tucked cuff'),
('tiered'),
('bishop collar'),
('button front'),
('pull on'),
('pleat'),
('split skirt front'),
('laced front'),
('gauntlet and armband'),
('upper arm'),
('set in sleeve'),
('2 part open sleeve with large cuff'),
('head dress'),
('shawl collar'),
('brimless hennin'),
('standing collar'),
('pleated cuff under'),
('slash opening'),
('front lacing'),
('hip'),
('mitts'),
('choli'),
('10 yard'),
('extra full'),
('scooped yolk'),
('hip and bust gore'),
('fitted yolk'),
('full cuffed sleeve'),
('full cap tapered sleeve'),
('coat sleeves with jockeys'),
('tie on'),
('taped'),
('long bow '),
('mock button front'),
('pull on '),
('tucked hem'),
('jewel neck'),
('criss cross strap'),
('Civil War'),
('working class'),
('Ever After'),
('Victorian'),
('mermaid'),
('dual princess seam slits'),
('spaghetti strap'),
('gored bust and hip')

select * from [tlkp_CutNames] 

